// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARxHI-B0palL8JP0PQqRDFStEw-8DycxA',
    appId: '1:606494228675:web:32db23f198c4aaf2c92276',
    messagingSenderId: '606494228675',
    projectId: 'shopply-6b1fd',
    authDomain: 'shopply-6b1fd.firebaseapp.com',
    storageBucket: 'shopply-6b1fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbx5Gdr1xYqUzwybahZvJ7CQ_nZAE54uI',
    appId: '1:606494228675:android:a45ce04a56fddae5c92276',
    messagingSenderId: '606494228675',
    projectId: 'shopply-6b1fd',
    storageBucket: 'shopply-6b1fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPY0ooXtTqd9gmfj1L98D8sGqf59NXHWg',
    appId: '1:606494228675:ios:c616e111b0b562fac92276',
    messagingSenderId: '606494228675',
    projectId: 'shopply-6b1fd',
    storageBucket: 'shopply-6b1fd.appspot.com',
    iosBundleId: 'com.example.shopply',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPY0ooXtTqd9gmfj1L98D8sGqf59NXHWg',
    appId: '1:606494228675:ios:c616e111b0b562fac92276',
    messagingSenderId: '606494228675',
    projectId: 'shopply-6b1fd',
    storageBucket: 'shopply-6b1fd.appspot.com',
    iosBundleId: 'com.example.shopply',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARxHI-B0palL8JP0PQqRDFStEw-8DycxA',
    appId: '1:606494228675:web:321107be929e1c73c92276',
    messagingSenderId: '606494228675',
    projectId: 'shopply-6b1fd',
    authDomain: 'shopply-6b1fd.firebaseapp.com',
    storageBucket: 'shopply-6b1fd.appspot.com',
  );

}